# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores de mascotas',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies de mascotas',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos de mascotas',
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('señas', models.TextField(blank=True, default='', null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Color')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Especie')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Genero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascotas',
                'verbose_name_plural': 'Feed de Mascotas',
            },
        ),
    ]
