# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_auto_20171014_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='edad',
            new_name='edad_años',
        ),
    ]
