# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_auto_20171014_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas de mascotas',
            },
        ),
    ]
