# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_mascota_raza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='raza',
        ),
    ]
