# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_auto_20171014_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
