# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-31 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_auto_20171014_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Posibles estados de mascota',
                'verbose_name': 'Estado de mascota',
            },
        ),
    ]
