# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
